In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/world-development-indicators-2026-03-21.csv", encoding='ISO-8859-1')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22745 entries, 0 to 22744
Data columns (total 54 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series Name    22742 non-null  object
 1   Series Code    22740 non-null  object
 2   Country Name   22740 non-null  object
 3   Country Code   22740 non-null  object
 4   1976 [YR1976]  22740 non-null  object
 5   1977 [YR1977]  22740 non-null  object
 6   1978 [YR1978]  22740 non-null  object
 7   1979 [YR1979]  22740 non-null  object
 8   1980 [YR1980]  22740 non-null  object
 9   1981 [YR1981]  22740 non-null  object
 10  1982 [YR1982]  22740 non-null  object
 11  1983 [YR1983]  22740 non-null  object
 12  1984 [YR1984]  22740 non-null  object
 13  1985 [YR1985]  22740 non-null  object
 14  1986 [YR1986]  22740 non-null  object
 15  1987 [YR1987]  22740 non-null  object
 16  1988 [YR1988]  22740 non-null  object
 17  1989 [YR1989]  22740 non-null  object
 18  1990 [YR1990]  22740 non-null  object
 19  1991 [YR1991]  22740 non-null  object
 20  1992 [YR1992]  22740 non-null  object
 21  1993 [YR1993]  22740 non-null  object
 22  1994 [YR1994]  22740 non-null  object
 23  1995 [YR1995]  22740 non-null  object
 24  1996 [YR1996]  22740 non-null  object
 25  1997 [YR1997]  22740 non-null  object
 26  1998 [YR1998]  22740 non-null  object
 27  1999 [YR1999]  22740 non-null  object
 28  2000 [YR2000]  22740 non-null  object
 29  2001 [YR2001]  22740 non-null  object
 30  2002 [YR2002]  22740 non-null  object
 31  2003 [YR2003]  22740 non-null  object
 32  2004 [YR2004]  22740 non-null  object
 33  2005 [YR2005]  22740 non-null  object
 34  2006 [YR2006]  22740 non-null  object
 35  2007 [YR2007]  22740 non-null  object
 36  2008 [YR2008]  22740 non-null  object
 37  2009 [YR2009]  22740 non-null  object
 38  2010 [YR2010]  22740 non-null  object
 39  2011 [YR2011]  22740 non-null  object
 40  2012 [YR2012]  22740 non-null  object
 41  2013 [YR2013]  22740 non-null  object
 42  2014 [YR2014]  22740 non-null  object
 43  2015 [YR2015]  22740 non-null  object
 44  2016 [YR2016]  22740 non-null  object
 45  2017 [YR2017]  22740 non-null  object
 46  2018 [YR2018]  22740 non-null  object
 47  2019 [YR2019]  22740 non-null  object
 48  2020 [YR2020]  22740 non-null  object
 49  2021 [YR2021]  22740 non-null  object
 50  2022 [YR2022]  22740 non-null  object
 51  2023 [YR2023]  22740 non-null  object
 52  2024 [YR2024]  22740 non-null  object
 53  2025 [YR2025]  22740 non-null  object
dtypes: object(54)
memory usage: 9.4+ MB

In [4]:
df['Series Name'].unique().tolist()

['Population, total',
 'Population growth (annual %)',
 'Surface area (sq. km)',
 'Poverty headcount ratio at national poverty lines (% of population)',
 'GNI, Atlas method (current US$)',
 'GNI per capita, Atlas method (current US$)',
 'GNI, PPP (current international $)',
 'GNI per capita, PPP (current international $)',
 'Income share held by lowest 20%',
 'Life expectancy at birth, total (years)',
 'Fertility rate, total (births per woman)',
 'Adolescent fertility rate (births per 1,000 women ages 15-19)',
 'Contraceptive prevalence, any method (% of married women ages 15-49)',
 'Births attended by skilled health staff (% of total)',
 'Mortality rate, under-5 (per 1,000 live births)',
 'Prevalence of underweight, weight for age (% of children under 5)',
 'Immunization, measles (% of children ages 12-23 months)',
 'Primary completion rate, total (% of relevant age group)',
 'School enrollment, secondary (% gross)',
 'School enrollment, primary and secondary (gross), gender parity index (GPI)',
 'Prevalence of HIV, total (% of population ages 15-49)',
 'Forest area (sq. km)',
 'Water productivity, total (constant 2015 US$ GDP per cubic meter of total freshwater withdrawal)',
 'Energy use (kg of oil equivalent per capita)',
 'Electric power consumption (kWh per capita)',
 'GDP (current US$)',
 'GDP growth (annual %)',
 'Inflation, GDP deflator (annual %)',
 'Agriculture, forestry, and fishing, value added (% of GDP)',
 'Industry (including construction), value added (% of GDP)',
 'Exports of goods and services (% of GDP)',
 'Imports of goods and services (% of GDP)',
 'Gross capital formation (% of GDP)',
 'Revenue, excluding grants (% of GDP)',
 'Market capitalization of listed domestic companies (% of GDP)',
 'Military expenditure (% of GDP)',
 'Mobile cellular subscriptions (per 100 people)',
 'High-technology exports (% of manufactured exports)',
 'Merchandise trade (% of GDP)',
 'Net barter terms of trade index (2015 = 100)',
 'External debt stocks, total (DOD, current US$)',
 'Total debt service (% of GNI)',
 'Net migration',
 'Personal remittances, paid (current US$)',
 'Foreign direct investment, net inflows (BoP, current US$)',
 'Net ODA received per capita (current US$)',
 'GDP per capita (current US$)',
 'Foreign direct investment, net (BoP, current US$)',
 'Inflation, consumer prices (annual %)',
 'Access to clean fuels and technologies for cooking (% of population)',
 'Access to clean fuels and technologies for cooking, rural (% of rural population)',
 'Access to clean fuels and technologies for cooking, urban (% of urban population)',
 'Access to electricity (% of population)',
 'Access to electricity, rural (% of rural population)',
 'Access to electricity, urban (% of urban population)',
 'Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+)',
 'Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)',
 'Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)',
 'Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)',
 'Account ownership at a financial institution or with a mobile-money-service provider, poorest 40% (% of population ages 15+)',
 'Account ownership at a financial institution or with a mobile-money-service provider, primary education or less (% of population ages 15+)',
 'Account ownership at a financial institution or with a mobile-money-service provider, richest 60% (% of population ages 15+)',
 'Account ownership at a financial institution or with a mobile-money-service provider, secondary education or more (% of population ages 15+)',
 'Account ownership at a financial institution or with a mobile-money-service provider, young adults (% of population ages 15-24)',
 'Adequacy of social insurance programs (% of total welfare of beneficiary households)',
 'Adequacy of social protection and labor programs (% of total welfare of beneficiary households)',
 'Adequacy of social safety net programs (% of total welfare of beneficiary households)',
 'Adequacy of unemployment benefits and ALMP (% of total welfare of beneficiary households)',
 'Adjusted net enrollment rate, primary (% of primary school age children)',
 'Adjusted net enrollment rate, primary, female (% of primary school age children)',
 'Adjusted net enrollment rate, primary, male (% of primary school age children)',
 'Adjusted net national income (annual % growth)',
 'Adjusted net national income (constant 2015 US$)',
 'Adjusted net national income (current US$)',
 'Adjusted net national income per capita (annual % growth)',
 'Adjusted net national income per capita (constant 2015 US$)',
 'Adjusted net national income per capita (current US$)',
 'Adjusted net savings, excluding particulate emission damage (% of GNI)',
 'Adjusted net savings, excluding particulate emission damage (current US$)',
 'Adjusted net savings, including particulate emission damage (% of GNI)',
 'Adjusted net savings, including particulate emission damage (current US$)',
 'Adjusted savings: carbon dioxide damage (% of GNI)',
 'Adjusted savings: carbon dioxide damage (current US$)',
 'Adjusted savings: consumption of fixed capital (% of GNI)',
 'Adjusted savings: consumption of fixed capital (current US$)',
 'Adjusted savings: education expenditure (% of GNI)',
 'Adjusted savings: education expenditure (current US$)',
 'Adjusted savings: energy depletion (% of GNI)',
 'Adjusted savings: energy depletion (current US$)',
 'Adjusted savings: gross savings (% of GNI)',
 'Adjusted savings: mineral depletion (% of GNI)',
 'Adjusted savings: mineral depletion (current US$)',
 'Adjusted savings: natural resources depletion (% of GNI)',
 'Adjusted savings: net forest depletion (% of GNI)',
 'Adjusted savings: net forest depletion (current US$)',
 'Adjusted savings: net national savings (% of GNI)',
 'Adjusted savings: net national savings (current US$)',
 'Adjusted savings: particulate emission damage (% of GNI)',
 'Adjusted savings: particulate emission damage (current US$)',
 'Adolescents out of school (% of lower secondary school age)',
 'Adolescents out of school, female (% of female lower secondary school age)',
 'Adolescents out of school, male (% of male lower secondary school age)',
 'Adults (ages 15+) and children (ages 0-14) newly infected with HIV',
 'Adults (ages 15-49) newly infected with HIV',
 'Age dependency ratio (% of working-age population)',
 'Age dependency ratio, old (% of working-age population)',
 'Age dependency ratio, young (% of working-age population)',
 'Agricultural irrigated land (% of total agricultural land)',
 'Agricultural land (% of land area)',
 'Agricultural land (sq. km)',
 'Agricultural raw materials exports (% of merchandise exports)',
 'Agricultural raw materials imports (% of merchandise imports)',
 'Agriculture, forestry, and fishing, value added (annual % growth)',
 'Agriculture, forestry, and fishing, value added (constant 2015 US$)',
 'Agriculture, forestry, and fishing, value added (constant LCU)',
 'Agriculture, forestry, and fishing, value added (current LCU)',
 'Agriculture, forestry, and fishing, value added (current US$)',
 'Agriculture, forestry, and fishing, value added per worker (constant 2015 US$)',
 'Air transport, freight (million ton-km)',
 'Air transport, passengers carried',
 'Air transport, registered carrier departures worldwide',
 'Alternative and nuclear energy (% of total energy use)',
 'Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)',
 'Annual freshwater withdrawals, domestic (% of total freshwater withdrawal)',
 'Annual freshwater withdrawals, industry (% of total freshwater withdrawal)',
 'Annual freshwater withdrawals, total (% of internal resources)',
 'Annual freshwater withdrawals, total (billion cubic meters)',
 'Annualized average growth rate in per capita real survey mean consumption or income, bottom 40% of population (%)',
 'Annualized average growth rate in per capita real survey mean consumption or income, total population (%)',
 'Antiretroviral therapy coverage (% of people living with HIV)',
 'Antiretroviral therapy coverage for PMTCT (% of pregnant women living with HIV)',
 'Aquaculture production (metric tons)',
 'Arable land (% of land area)',
 'Arable land (hectares per person)',
 'Arable land (hectares)',
 'ARI treatment (% of children under 5 taken to a health provider)',
 'Armed forces personnel (% of total labor force)',
 'Armed forces personnel, total',
 'Arms exports (SIPRI trend indicator values)',
 'Arms imports (SIPRI trend indicator values)',
 'Asylum-seekers by country or territory of asylum',
 'Asylum-seekers by country or territory of origin',
 'Automated teller machines (ATMs) (per 100,000 adults)',
 'Average precipitation in depth (mm per year)',
 'Average time to clear exports through customs (days)',
 'Average time to clear imports through customs (days)',
 'Average transaction cost of sending remittances from a specific country (%)',
 'Average transaction cost of sending remittances to a specific country (%)',
 'Average working hours of children, study and work, ages 7-14 (hours per week)',
 'Average working hours of children, study and work, female, ages 7-14 (hours per week)',
 'Average working hours of children, study and work, male, ages 7-14 (hours per week)',
 'Average working hours of children, working only, ages 7-14 (hours per week)',
 'Average working hours of children, working only, female, ages 7-14 (hours per week)',
 'Average working hours of children, working only, male, ages 7-14 (hours per week)',
 'Bank capital to assets ratio (%)',
 'Bank liquid reserves to bank assets ratio (%)',
 'Bank nonperforming loans to total gross loans (%)',
 'Battle-related deaths (number of people)',
 'Benefit incidence of social insurance programs to poorest quintile (% of total social insurance benefits)',
 'Benefit incidence of social protection and labor programs to poorest quintile (% of total SPL benefits)',
 'Benefit incidence of social safety net programs to poorest quintile (% of total safety net benefits)',
 'Benefit incidence of unemployment benefits and ALMP to poorest quintile (% of total U/ALMP benefits)',
 'Binding coverage, all products (%)',
 'Binding coverage, manufactured products (%)',
 'Binding coverage, primary products (%)',
 'Bird species, threatened',
 'Birth rate, crude (per 1,000 people)',
 'Borrowers from commercial banks (per 1,000 adults)',
 'Bound rate, simple mean, all products (%)',
 'Bound rate, simple mean, manufactured products (%)',
 'Bound rate, simple mean, primary products (%)',
 'B-READY: Business Entry Pillar 1: Quality of Regulations for Business Entry',
 'B-READY: Business Entry Pillar 2: Digital Public Services and Transparency of Information for Business Entry',
 'B-READY: Business Entry Pillar 3: Operational Efficiency of Business Entry',
 'B-READY: Business Entry: Overall Score',
 'B-READY: Business Insolvency Pillar 1: Quality of Regulations for Judicial Insolvency Proceedings',
 'B-READY: Business Insolvency Pillar 2: Quality of Institutional and Operational Infrastructure for Judicial Insolvency Proceedings',
 'B-READY: Business Insolvency Pillar 3: Operational Efficiency of Resolving Judicial Insolvency Proceedings',
 'B-READY: Business Insolvency: Overall Score',
 'B-READY: Business Location Pillar 1: Quality of Regulations for Business Location',
 'B-READY: Business Location Pillar 2: Quality of Public Services and Transparency of Information for Business Location',
 'B-READY: Business Location Pillar 3: Operational Efficiency of Establishing a Business Location',
 'B-READY: Business Location: Overall Score',
 'B-READY: Dispute Resolution Pillar 1: Quality of Regulations for Dispute Resolution',
 'B-READY: Dispute Resolution Pillar 2: Public Services for Dispute Resolution',
 'B-READY: Dispute Resolution Pillar 3:  Ease of Resolving a Commercial Dispute',
 'B-READY: Dispute Resolution: Overall Score',
 'B-READY: Financial Services Pillar 1: Quality of Regulations for Financial Services',
 'B-READY: Financial Services Pillar 2: Accessibility of Information in Credit Infrastructure',
 'B-READY: Financial Services Pillar 3: Operational Efficiency of Receiving Financial Services',
 'B-READY: Financial Services: Overall Score',
 'B-READY: International Trade Pillar 1: Quality of Regulations for International Trade',
 'B-READY: International Trade Pillar 2: Quality of Public Services for the Facilitation of International Trade',
 'B-READY: International Trade Pillar 3: Efficiency of Importing Goods, Exporting Goods, and Engaging in Digital Trade',
 'B-READY: International Trade: Overall Score',
 'B-READY: Labor Pillar 1: Quality of Labor Regulations',
 'B-READY: Labor Pillar 2: Adequacy of Public Services for Labor',
 'B-READY: Labor Pillar 3: Operational Efficiency of Labor Regulations and Public Services in Practice',
 'B-READY: Labor: Overall Score',
 'B-READY: Market Competition Pillar 1: Quality of Regulations that Promote Market Competition',
 'B-READY: Market Competition Pillar 2: Public Services that Promote Market Competition',
 'B-READY: Market Competition Pillar 3:  Implementation of Key Services Promoting Market Competition',
 'B-READY: Market Competition: Overall Score',
 'B-READY: Pillar 1: Regulatory Framework',
 'B-READY: Pillar 2: Public Services',
 'B-READY: Pillar 3: Operational Efficiency',
 'B-READY: Taxation Pillar 1: Quality of Regulations on Taxation',
 'B-READY: Taxation Pillar 2: Public Services Provided by the Tax Administration',
 'B-READY: Taxation Pillar 3: Operational Efficiency of Tax Systems in Practice',
 'B-READY: Taxation: Overall Score',
 'B-READY: Utility Services Pillar 1: Quality of Regulations on Utility Services',
 'B-READY: Utility Services Pillar 2: Quality of Governance and Transparency of Utility Services',
 'B-READY: Utility Services Pillar 3: Operational Efficiency of Utility Service Provision',
 'B-READY: Utility Services: Overall Score',
 'Bribery incidence (% of firms experiencing at least one bribe payment request)',
 'Broad money (% of GDP)',
 'Broad money (current LCU)',
 'Broad money growth (annual %)',
 'Broad money to total reserves ratio',
 'Capture fisheries production (metric tons)',
 'Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990)',
 'Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e)',
 'Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita)',
 'Carbon dioxide (CO2) emissions from Agriculture (Mt CO2e)',
 'Carbon dioxide (CO2) emissions from Building (Energy) (Mt CO2e)',
 'Carbon dioxide (CO2) emissions from Fugitive Emissions (Energy) (Mt CO2e)',
 'Carbon dioxide (CO2) emissions from Industrial Combustion (Energy) (Mt CO2e)',
 'Carbon dioxide (CO2) emissions from Industrial Processes (Mt CO2e)',
 'Carbon dioxide (CO2) emissions from Power Industry (Energy) (Mt CO2e)',
 'Carbon dioxide (CO2) emissions from Transport (Energy) (Mt CO2e)',
 'Carbon dioxide (CO2) emissions from Waste (Mt CO2e)',
 'Carbon dioxide (CO2) net fluxes from LULUCF - Deforestation (Mt CO2e)',
 'Carbon dioxide (CO2) net fluxes from LULUCF - Forest Land (Mt CO2e)',
 'Carbon dioxide (CO2) net fluxes from LULUCF - Organic Soil (Mt CO2e)',
 'Carbon dioxide (CO2) net fluxes from LULUCF - Other Land (Mt CO2e)',
 'Carbon dioxide (CO2) net fluxes from LULUCF - Total excluding non-tropical fires (Mt CO2e)',
 'Carbon intensity of GDP (kg CO2e per 2021 PPP $ of GDP)',
 'Carbon intensity of GDP (kg CO2e per constant 2015 US$ of GDP)',
 'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)',
 'Cause of death, by injury (% of total)',
 'Cause of death, by non-communicable diseases (% of total)',
 'Central government debt, total (% of GDP)',
 'Central government debt, total (current LCU)',
 'Cereal production (metric tons)',
 'Cereal yield (kg per hectare)',
 'Changes in inventories (constant LCU)',
 'Changes in inventories (current LCU)',
 'Changes in inventories (current US$)',
 'Charges for the use of intellectual property, payments (BoP, current US$)',
 'Charges for the use of intellectual property, receipts (BoP, current US$)',
 'Chemicals (% of value added in manufacturing)',
 'Child employment in agriculture (% of economically active children ages 7-14)',
 'Child employment in agriculture, female (% of female economically active children ages 7-14)',
 'Child employment in agriculture, male (% of male economically active children ages 7-14)',
 'Child employment in manufacturing (% of economically active children ages 7-14)',
 'Child employment in manufacturing, female (% of female economically active children ages 7-14)',
 'Child employment in manufacturing, male (% of male economically active children ages 7-14)',
 'Child employment in services (% of economically active children ages 7-14)',
 'Child employment in services, female (% of female economically active children ages 7-14)',
 'Child employment in services, male (% of male economically active children ages 7-14)',
 'Children (0-14) living with HIV',
 'Children (ages 0-14) newly infected with HIV',
 'Children in employment, female (% of female children ages 7-14)',
 'Children in employment, male (% of male children ages 7-14)',
 'Children in employment, self-employed (% of children in employment, ages 7-14)',
 'Children in employment, self-employed, female (% of female children in employment, ages 7-14)',
 'Children in employment, self-employed, male (% of male children in employment, ages 7-14)',
 'Children in employment, study and work (% of children in employment, ages 7-14)',
 'Children in employment, study and work, female (% of female children in employment, ages 7-14)',
 'Children in employment, study and work, male (% of male children in employment, ages 7-14)',
 'Children in employment, total (% of children ages 7-14)',
 'Children in employment, unpaid family workers (% of children in employment, ages 7-14)',
 'Children in employment, unpaid family workers, female (% of female children in employment, ages 7-14)',
 'Children in employment, unpaid family workers, male (% of male children in employment, ages 7-14)',
 'Children in employment, wage workers (% of children in employment, ages 7-14)',
 'Children in employment, wage workers, female (% of female children in employment, ages 7-14)',
 'Children in employment, wage workers, male (% of male children in employment, ages 7-14)',
 'Children in employment, work only (% of children in employment, ages 7-14)',
 'Children in employment, work only, female (% of female children in employment, ages 7-14)',
 'Children in employment, work only, male (% of male children in employment, ages 7-14)',
 'Children out of school (% of primary school age)',
 'Children out of school, female (% of female primary school age)',
 'Children out of school, male (% of male primary school age)',
 'Children out of school, primary',
 'Children out of school, primary, female',
 'Children out of school, primary, male',
 'Children with fever receiving antimalarial drugs (% of children under age 5 with fever)',
 'Claims on central government (annual growth as % of broad money)',
 'Claims on central government, etc. (% GDP)',
 'Claims on other sectors of the domestic economy (% of GDP)',
 'Claims on other sectors of the domestic economy (annual growth as % of broad money)',
 'Claims on private sector (annual growth as % of broad money)',
 'Coal rents (% of GDP)',
 'Combustible renewables and waste (% of total energy)',
 'Commercial bank branches (per 100,000 adults)',
 'Commercial banks and other lending (PPG + PNG) (NFL, current US$)',
 'Commercial service exports (current US$)',
 'Commercial service imports (current US$)',
 'Communications, computer, etc. (% of service exports, BoP)',

In [5]:
# Top 20 World Bank Development Indicators
world_bank_indicators = [
    "NY.GDP.MKTP.KD.ZG",    # 1. GDP growth (annual %)
    "NY.GDP.MKTP.CD",       # 2. GDP (current US$)
    "NY.GDP.PCAP.CD",       # 3. GDP per capita (current US$)
    "NY.GNP.PCAP.CD",       # 4. GNI per capita, Atlas method (current US$)
    "NY.GNS.ICTR.GN.ZS",    # 5. Gross Savings (% of GNI)
    "SI.POV.NAHC",          # 6. Poverty headcount ratio at national poverty lines
    "SI.POV.LMIC",          # 7. Poverty headcount ratio at $3.65 a day (2017 PPP)
    "SI.DST.FRST.20",       # 8. Income share held by lowest 20%
    "SL.UEM.TOTL.ZS",       # 9. Unemployment, total (% of total labor force)
    "SL.TLF.CACT.ZS",       # 10. Labor force participation rate, total (15+)
    "SE.PRM.ENRR",          # 11. School enrollment, primary (% gross)
    "SE.ADT.1524.LT.ZS",    # 12. Literacy rate, youth total (15-24)
    "SP.DYN.LE00.IN",       # 13. Life expectancy at birth, total (years)
    "SH.DYN.MORT",          # 14. Mortality rate, under-5 (per 1,000 live births)
    "SP.POP.TOTL",          # 15. Population, total
    "EG.ELC.ACCS.ZS",       # 16. Access to electricity (% of population)
    "EN.ATM.CO2E.PC",       # 17. CO2 emissions (metric tons per capita)
    "AG.LND.FRST.ZS",       # 18. Forest area (% of land area)
    "NE.EXP.GNFS.ZS",       # 19. Exports of goods and services (% of GDP)
    "BX.KLT.DINV.CD.WD"     # 20. Foreign direct investment, net inflows (BoP)
]

In [6]:
subset = df[df['Series Code'].isin(world_bank_indicators)]

In [7]:
subset

,Series Name,Series Code,Country Name,Country Code,1976 [YR1976],1977 [YR1977],1978 [YR1978],1979 [YR1979],1980 [YR1980],1981 [YR1981],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,"Population, total",SP.POP.TOTL,United States,USA,218035000,220239000,222585000,225055000,227225000,229466000,...,324353340,326608609,328529577,330226227,331577720,332099760,334017321,336806231,340110988,..
1,"Population, total",SP.POP.TOTL,United Kingdom,GBR,56211968,56193492,56196504,56246951,56314216,56333829,...,65607000,65966000,66289000,66631000,66744000,66984000,67604000,68492000,69226000,..
2,"Population, total",SP.POP.TOTL,China,CHN,930685000,943455000,956165000,969005000,981235000,993885000,...,1387790000,1396215000,1402760000,1407745000,1411100000,1412360000,1412175000,1410710000,1408975000,..
3,"Population, total",SP.POP.TOTL,"Macao SAR, China",MAC,235600,232950,232400,235200,239650,244800,...,652500,648400,658900,672000,685400,682500,677300,678800,687000,..
4,"Population, total",SP.POP.TOTL,"Hong Kong SAR, China",HKG,4518000,4583700,4667500,4929700,5063100,5183400,...,7336600,7393200,7452600,7507900,7481000,7413100,7346100,7536100,7524100,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22045,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,Russian Federation,RUS,..,..,..,..,..,..,...,5.591,5.238,4.871,4.513,5.62,4.749,3.867,3.076,2.43,2.133
22046,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,Canada,CAN,..,..,..,..,..,..,...,7.038,6.426,5.837,5.69,9.657,7.527,5.279,5.415,6.351,6.907
22047,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,Australia,AUS,..,..,..,..,..,..,...,5.711,5.592,5.345,5.143,6.394,5.022,3.728,3.668,3.942,4.09
22048,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,Bangladesh,BGD,..,..,..,..,..,..,...,4.35,4.372,4.439,4.504,5.539,5.457,4.593,3.352,3.635,3.778
22049,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,Pakistan,PAK,..,..,..,..,..,..,...,2.285,3.204,4.083,4.83,5.994,6.338,5.291,5.237,5.492,5.42

In [8]:
subset['Country Name'].unique().tolist()

['United States',
 'United Kingdom',
 'China',
 'Macao SAR, China',
 'Hong Kong SAR, China',
 'Germany',
 'India',
 'Japan',
 'France',
 'Italy',
 'Russian Federation',
 'Canada',
 'Australia',
 'Bangladesh',
 'Pakistan']

In [9]:
subset.columns

Index(['Series Name', 'Series Code', 'Country Name', 'Country Code',
       '1976 [YR1976]', '1977 [YR1977]', '1978 [YR1978]', '1979 [YR1979]',
       '1980 [YR1980]', '1981 [YR1981]', '1982 [YR1982]', '1983 [YR1983]',
       '1984 [YR1984]', '1985 [YR1985]', '1986 [YR1986]', '1987 [YR1987]',
       '1988 [YR1988]', '1989 [YR1989]', '1990 [YR1990]', '1991 [YR1991]',
       '1992 [YR1992]', '1993 [YR1993]', '1994 [YR1994]', '1995 [YR1995]',
       '1996 [YR1996]', '1997 [YR1997]', '1998 [YR1998]', '1999 [YR1999]',
       '2000 [YR2000]', '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]',
       '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]',
       '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]',
       '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]',
       '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]',
       '2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]',
       '2024 [YR2024]', '2025 [YR2025]'],
      dtype='object')

In [10]:
columns = ['Series Name', 'Series Code', 'Country Name', 'Country Code',
       '1976', '1977', '1978', '1979',
       '1980', '1981', '1982', '1983',
       '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991',
       '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999',
       '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019',
       '2020', '2021', '2022', '2023',
       '2024', '2025']

In [11]:
subset.columns = columns

In [12]:
subset.head()

,Series Name,Series Code,Country Name,Country Code,1976,1977,1978,1979,1980,1981,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,"Population, total",SP.POP.TOTL,United States,USA,218035000,220239000,222585000,225055000,227225000,229466000,...,324353340,326608609,328529577,330226227,331577720,332099760,334017321,336806231,340110988,..
1,"Population, total",SP.POP.TOTL,United Kingdom,GBR,56211968,56193492,56196504,56246951,56314216,56333829,...,65607000,65966000,66289000,66631000,66744000,66984000,67604000,68492000,69226000,..
2,"Population, total",SP.POP.TOTL,China,CHN,930685000,943455000,956165000,969005000,981235000,993885000,...,1387790000,1396215000,1402760000,1407745000,1411100000,1412360000,1412175000,1410710000,1408975000,..
3,"Population, total",SP.POP.TOTL,"Macao SAR, China",MAC,235600,232950,232400,235200,239650,244800,...,652500,648400,658900,672000,685400,682500,677300,678800,687000,..
4,"Population, total",SP.POP.TOTL,"Hong Kong SAR, China",HKG,4518000,4583700,4667500,4929700,5063100,5183400,...,7336600,7393200,7452600,7507900,7481000,7413100,7346100,7536100,7524100,..

In [13]:
json_path = "../data/world-development-indicators-subset-2026-03-21.json"
subset.to_json(json_path)

In [14]:
records = subset.to_records()

In [15]:
records

rec.array([(    0, 'Population, total', 'SP.POP.TOTL', 'United States', 'USA', '218035000', '220239000', '222585000', '225055000', '227225000', '229466000', '231664000', '233792000', '235825000', '237924000', '240133000', '242289000', '244499000', '246819000', '249623000', '252981000', '256514000', '259919000', '263126000', '266278000', '269394000', '272657000', '275854000', '279040000', '282162411', '284968955', '287625193', '290107933', '292805298', '295516599', '298379912', '301231207', '304093966', '306771529', '309378227', '311839461', '314339099', '316726282', '319257560', '321815121', '324353340', '326608609', '328529577', '330226227', '331577720', '332099760', '334017321', '336806231', '340110988', '..'),
           (    1, 'Population, total', 'SP.POP.TOTL', 'United Kingdom', 'GBR', '56211968', '56193492', '56196504', '56246951', '56314216', '56333829', '56313641', '56332848', '56422072', '56550268', '56681396', '56802050', '56928327', '57076711', '57247586', '57424897', '57580402', '57718614', '57865745', '58019030', '58166950', '58316954', '58487141', '58682466', '58892514', '59119673', '59370479', '59647577', '59987905', '60401206', '60846820', '61322463', '61806995', '62276270', '62766365', '63258810', '63711000', '64139000', '64620000', '65088000', '65607000', '65966000', '66289000', '66631000', '66744000', '66984000', '67604000', '68492000', '69226000', '..'),
           (    2, 'Population, total', 'SP.POP.TOTL', 'China', 'CHN', '930685000', '943455000', '956165000', '969005000', '981235000', '993885000', '1008630000', '1023310000', '1036825000', '1051040000', '1066790000', '1084035000', '1101630000', '1118650000', '1135185000', '1150780000', '1164970000', '1178440000', '1191835000', '1204855000', '1217550000', '1230075000', '1241935000', '1252735000', '1262645000', '1271850000', '1280400000', '1288400000', '1296075000', '1303720000', '1311020000', '1317885000', '1324655000', '1331260000', '1337705000', '1345035000', '1354190000', '1363240000', '1371860000', '1379860000', '1387790000', '1396215000', '1402760000', '1407745000', '1411100000', '1412360000', '1412175000', '1410710000', '1408975000', '..'),
           (    3, 'Population, total', 'SP.POP.TOTL', 'Macao SAR, China', 'MAC', '235600', '232950', '232400', '235200', '239650', '244800', '254650', '269300', '282850', '289700', '296050', '306850', '316000', '325100', '334950', '351650', '370900', '384000', '396800', '409300', '415100', '417300', '422300', '427400', '430600', '433900', '438400', '443600', '454700', '473500', '498900', '520900', '540700', '535000', '537000', '549600', '567900', '591900', '621700', '642900', '652500', '648400', '658900', '672000', '685400', '682500', '677300', '678800', '687000', '..'),
           (    4, 'Population, total', 'SP.POP.TOTL', 'Hong Kong SAR, China', 'HKG', '4518000', '4583700', '4667500', '4929700', '5063100', '5183400', '5264500', '5345100', '5397900', '5456200', '5524600', '5580500', '5627600', '5686200', '5704500', '5752000', '5800500', '5901000', '6035400', '6156100', '6435500', '6489300', '6543700', '6606500', '6665000', '6714300', '6744100', '6730800', '6783500', '6813200', '6857100', '6916300', '6957800', '6972800', '7024200', '7071600', '7150100', '7178900', '7229500', '7291300', '7336600', '7393200', '7452600', '7507900', '7481000', '7413100', '7346100', '7536100', '7524100', '..'),
           (    5, 'Population, total', 'SP.POP.TOTL', 'Germany', 'DEU', '78336950', '78159814', '78091820', '78126350', '78288576', '78407907', '78333366', '78128282', '77858685', '77684873', '77720436', '77839920', '78144619', '78751283', '79433029', '80013896', '80624598', '81156363', '81438348', '81678051', '81914831', '82034771', '82047195', '82100243', '82211508', '82349925', '82488495', '82534176', '82516260', '82469422', '82376451', '82266372', '82110097', '81902307', '81776930', '80274983', '80425823', '80645605', '80982500', '81686611', '82348669', '82657002', '82905782', '83092962', '83160871', '83196078', '83177813', '83287273', '83516593', '..'),
           (    6, 'Population, total', 'SP.POP.TOTL', 'India', 'IND', '625861883', '640801103', '655728229', '671155747', '687354025', '703696250', '720313473', '737372681', '754875449', '772647793', '790689978', '808931270', '827342990', '846039529', '864972221', '883927600', '902957070', '922118387', '941163767', '960301044', '979678458', '999133762', '1018665080', '1038225823', '1057922733', '1077898575', '1097600380', '1116803006', '1135991513', '1154676322', '1172878890', '1190676021', '1207930964', '1225524753', '1243481564', '1261224954', '1278674502', '1295829511', '1312277191', '1328024498', '1343944296', '1359657400', '1374659064', '1389030312', '1402617695', '1414203896', '1425423212', '1438069596', '1450935791', '..'),
           (    7, 'Population, total', 'SP.POP.TOTL', 'Japan', 'JPN', '112775000', '113872000', '114913000', '115890000', '116807000', '117661000', '118480000', '119307000', '120083000', '120837000', '121482000', '122069000', '122578000', '123069000', '123478000', '123964000', '124425000', '124829000', '125178000', '125472000', '125757000', '126057000', '126400000', '126631000', '126843000', '127149000', '127445000', '127718000', '127761000', '127773000', '127854000', '128001000', '128063000', '128047000', '128070000', '127833000', '127629000', '127445000', '127276000', '127141000', '127076000', '126972000', '126811000', '126633000', '126261000', '125681593', '125124989', '124516650', '123975371', '..'),
           (    8, 'Population, total', 'SP.POP.TOTL', 'France', 'FRA', '54232383', '54486467', '54734030', '54979851', '55274184', '55603353', '55806789', '56108330', '56383085', '56665619', '56956002', '57266167', '57598186', '57943062', '58261012', '58554242', '58846584', '59103094', '59324863', '59541294', '59754504', '59968066', '60190684', '60501986', '60918661', '61364377', '61812142', '62249855', '62707588', '63180854', '63622342', '64016890', '64375116', '64706436', '65026211', '65340830', '65657659', '65997932', '66312067', '66548272', '66724104', '66918020', '67158348', '67382061', '67601110', '67842811', '68184457', '68372286', '68551653', '..'),
           (    9, 'Population, total', 'SP.POP.TOTL', 'Italy', 'ITA', '55718260', '55955411', '56155143', '56317749', '56433883', '56501675', '56543548', '56564074', '56576718', '56593071', '56596155', '56601931', '56629288', '56671781', '56719240', '56758521', '56797087', '56831821', '56843400', '56844303', '56860281', '56890372', '56906744', '56916317', '56942108', '56976981', '57089824', '57399184', '57828179', '58166682', '58399861', '58756247', '59211181', '59555454', '59819407', '60026841', '60191247', '60311613', '60320707', '60229605', '60115223', '60002252', '60148658', '59729081', '59438851', '59133173', '59013667', '58984216', '58952704', '..'),
           (   10, 'Population, total', 'SP.POP.TOTL', 'Russian Federation', 'RUS', '135147000', '136100000', '137060000', '138027000', '139010000', '139941000', '140823000', '141668000', '142745000', '143858000', '144894000', '145908000', '146857000', '147721000', '147969406', '148394216', '148538197', '148458777', '148407912', '148375787', '148160129', '147915361', '147670784', '147214776', '146596869', '145976482', '145306497', '144648618', '144067316', '143518814', '143049637', '142805114', '142742366', '142785348', '142849468', '143018195', '143378447', '143805638', '144237223', '144640716', '145015460', '145293260', '145398106', '145453291', '145245148', '144746762', '144236933', '143826130', '143533851', '..'),
           (   11, 'Population, total', 'SP.POP.TOTL', 'Canada', 'CAN', '23449808', '23725843', '23963203', '24201544', '24515667', '24819915', '25116942', '25366451', '25607053', '25842116', '26100278', '26446601', '26791747', '27276781', '27691138', '28037420', '28371264', '28684764', '29000663', '29302311', '29610218', '29905948', '30155173', '30401286', '30685730', '31020855', '31359199', '31642461', '31938807', '32242732', '32571193', '32888886', '33247298', '33630069', '34005902', '34339221', '34713395', '35080992', '35434066', '35704498', '36110803', '36545075', '37072620', '37618495', '38028638', '38239864', '38935934', '40083484', '41288599', '..'),
           (   12, 'Population, total', 'SP.POP.TOTL', 'Australia', 'AUS', '14033000', '14192000', '14358000', '14514000', '14692000', '14923260', '15184247', '15393472', '15579391', '15788312', '16018350', '16263874', '16532164', '16814416', '17065128', '17284036', '17478635', '17634808', '17805468', '18004882', '18224767', '18423037', '18607584', '18812264', '19028802', '19274701', '19495210', '19720737', '19932722', '20176844', '20450966', '20827622', '21249199', '21691653', '22031750', '22340024', '22733465', '23128129', '23475686', '23815995', '24190907', '24592588', '24963258', '25334826', '25649248', '25685412', '26018721', '26659922', '27196812', '..'),
           (   13, 'Population, total', 'SP.POP.TOTL', 'Bangladesh', 'BGD', '79855318', '81867264', '83889655', '85935072', '88016432', '90303105', '92814507', '95335155', '97814966', '100253825', '102635572', '104959291', '107216008', '109433799', '111633717', '113787109', '115952192', '118132360', '120343179', '122600370', '124862179', '127198069', '129622332', '132108065', '134544304', '136805810', '138933658', '140970351', '142902856', '144715786', '146405973', '147989278', '149474264', '150873714', '152201981', '153591076', '155070101', '156532141', '157964929', '159383179', '160811932', '162186147', '163523103', '164913055', '166298024', '167658854', '169384897', '171466990', '173562364', '..'),
           (   14, 'Population, total', 'SP.POP.TOTL', 'Pakistan', 'PAK', '71620254', '73901827', '76307379', '78997039', '82291010', '85802049', '89089246', '92227711', '95164936', '98229285', '101606764', '105130717', '108724739', '112336629', '116155576', '120060406', '123546848', '127020117', '130748083', '134582253', '138557092', '142531804', '146522356', '150565377', '154879127', '159270907', '163222549', '167110248', '171286000', '175453212', '179682690', '184493231', '189499113', '194376534', '199239047', '203746065', '207667125', '211073978', '214264647', '217290883', '220138869', '223273967', '226928892', '230800899', '235001746', '239477801', '243700667', '247504495', '251269164', '..'),
           (   45, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'United States', 'USA', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..'),
           (   46, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'United Kingdom', 'GBR', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '17', '18.6', '..', '..', '..', '..', '..', '..', '..', '..'),
           (   47, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'China', 'CHN', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '49.8', '..', '..', '..', '..', '30.2', '..', '..', '..', '..', '17.2', '12.7', '10.2', '8.5', '7.2', '5.7', '4.5', '3.1', '1.7', '0.6', '0', '..', '..', '..', '..', '..'),
           (   48, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'Macao SAR, China', 'MAC', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..'),
           (   49, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'Hong Kong SAR, China', 'HKG', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..'),
           (   50, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'Germany', 'DEU', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '16.1', '16', '14.8', '..', '..', '..', '..'),
           (   51, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'India', 'IND', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '45.3', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '37.2', '..', '..', '..', '..', '29.8', '..', '21.9', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..'),
           (   52, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'Japan', 'JPN', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..'),
           (   53, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'France', 'FRA', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '13.8', '..', '15.6', '..', '..', '..', '..'),
           (   54, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'Italy', 'ITA', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '18.9', '19.2', '19.3', '19.5', '18.9', '18.4', '18.7', '19.8', '19.5', '19.3', '19.4', '19.9', '20.6', '20.3', '20.3', '20.1', '20', '20.1', '20.1', '..', '..', '..', '..'),
           (   55, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'Russian Federation', 'RUS', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '29', '..', '24.6', '20.3', '17.6', '17.8', '15.2', '13.3', '13.4', '13', '12.5', '12.7', '10.7', '10.8', '11.2', '13.3', '13.3', '13.2', '12.6', '12.3', '12.1', '..', '..', '..', '..', '..'),
           (   56, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'Canada', 'CAN', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..'),
           (   57, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'Australia', 'AUS', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..'),
           (   58, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'Bangladesh', 'BGD', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '56.6', '..', '..', '..', '50.1', '..', '..', '..', '..', '48.9', '..', '..', '..', '..', '40', '..', '..', '..', '..', '31.5', '..', '..', '..', '..', '..', '24.3', '..', '..', '..', '..', '..', '18.7', '..', '..', '..'),
           (   59, 'Poverty headcount ratio at national poverty lines (% of population)', 'SI.POV.NAHC', 'Pakistan', 'PAK', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '..', '64.3', '..', '..', '51.7', '50.4', '..', '44.1', '..', '..', '36.8', '36.3', '..', '29.5', '..', '24.3', '..', '..', '21.9', '..', '..', '..', '..', '..', '..', '..'),
           (   75, 'GNI per capita, Atlas method (current US$)', 'NY.GNP.PCAP.CD', 'United States', 'USA', '8960', '9590', '10760', '12200', '13390', '14360', '14220', '14570', '16210', '17460', '19110', '21390', '23490', '23770', '24060', '24270', '25680', '26390', '27660', '29040', '30270', '31280', '32040', '33680', '35960', '36710', '37320', '39770', '43520', '46190', '47850', '48530', '49110', '47910', '49180', '50620', '52610', '53830', '55600', '56400', '56900', '58920', '63020', '65880', '64920', '71730', '77330', '80000', '83490', '..'),
           (   76, 'GNI per capita, Atlas method (current US$)', 'NY.GNP.PCAP.CD', 'United Kingdom', 'GBR', '5050', '5250', '5940', '7540', '9550', '10660', '10690', '9870', '9320', '9180', '10330', '12730', '16120', '17390', '18640', '19450', '21690', '21650', '22210', '21360', '22970', '25630', '27040', '28210', '29550', '29190', '29260', '32370', '37910', '42840', '44960', '47640', '48720', '44370', '42010', '41240', '41940', '42960', '44780', '44630', '43310', '42140', '42540', '43640', '39340', '45870', '49720', '48830', '49470', '..'),
           (   77, 'GNI per capita, Atlas method (current US$)', 'NY.GNP.PCAP.CD', 'China', 'CHN', '190', '200', '200', '210', '220', '220', '220', '220', '250', '290', '310', '320', '330', '320', '330', '360', '400', '420', '470', '540', '660', '760', '800', '860', '950', '1020', '1130', '1300', '1530', '1790', '2090', '2550', '3140', '3740', '4410', '5130', '6010', '6860', '7600', '8040', '8360', '8830', '9720', '10510', '10740', '12220', '13170', '13750', '13660', '..'),
           (   78, 'GNI per capita, Atlas method (current US$)', 'NY.GNP.PCAP.CD', 'Macao SAR, China', 'MAC', '..', '..', '..', '..', '..', '..', '..', '..', '4590', '4500', '5220', '6540', '7600', '8270', '9210', '10050', '12280', '13800', '15260', '16420', '16580', '16670', '15230', '14330', '14620', '15910', '16670', '18510', '23050', '24430', '25920', '33070', '32190', '35520', '45370', '54620', '60370', '67830', '68530', '57990', '59670', '66940', '72850', '71690', '43910', '46330', '45390', '65040', '..', '..'),
           (   79, 'GNI per capita, Atlas method (current US$)', 'NY.GNP.PCAP.CD', 'Hong Kong SAR, China', 'HKG', '2900', '3340', '3930', '4700', '5730', '6360', '6290', '5890', '6170', '6090', '7230', '9080', '10770', '11550', '12660', '14320', '16560', '19560', '21820', '23570', '24140', '26080', '25110', '25800', '26930', '26350', '25270', '26340', '28120', '28890', '30290', '32070', '33950', '32350', '33620', '35690', '36340', '38570', '40240', '41180', '42970', '46380', '50050', '50480', '48550', '54380', '54000', '54910', '57070', '..'),

In [16]:
import json

grouped_data = {}

# We extract the year strings dynamically from your columns list (skipping the first 4 metadata columns)
years = columns[4:]

for record in records:
    series_name = record[1]
    series_code = record[2]
    country_name = record[3]  # You can inject this below if you want name metadata!
    country_code = record[4]

    if country_code in ['MAC', 'HKG']:
        continue
    
    # 1. Initialize the Series block if it's the first time we've encountered it
    if series_code not in grouped_data:
        grouped_data[series_code] = {
            "indicatorName": series_name,
            "data": {}
        }
        
    # 2. Iterate through all 50+ trailing years for this specific country
    year_timeline = {}
    for i, year in enumerate(years):
        val = record[5 + i] # Offsetting by 5 to jump past the ID & metadata strings
        
        # Clean '..' blank strings to actual Python None (JSON null)
        if val == '..' or not val:
            parsed_val = None
        # Convert numeric strings into floats/ints so they graph properly
        elif str(val).replace('.', '', 1).isdigit() or str(val).replace('-', '', 1).replace('.', '', 1).isdigit():
            parsed_val = float(val) if '.' in str(val) else int(val)
        else:
            parsed_val = val
            
        year_timeline[year] = parsed_val
        
    # 3. Attach this country's timeline inside the parent Series block
    grouped_data[series_code]["data"][country_code] = year_timeline


# Dump to cleanly indented JSON 
with open('../data/world-development-indicators-grouped.json', 'w') as f:
    json.dump(grouped_data, f, indent=2)
    
print(f"Successfully grouped {len(records)} records into {len(grouped_data.keys())} indicator categories!")

Successfully grouped 285 records into 19 indicator categories!