In [112]:
import json
import pandas as pd

In [113]:
df = pd.read_csv("../data/data-gov-india/railways-electrified-route-km-1965-2014.csv")

In [114]:
df.head()

,Year,FY,Single Line - Broad Gauge,Single Line - Metre Gauge,Double/Triple etc. - Broad Gauge,Double/Triple etc. - Metre Gauge,Total
0,1964-65,1965,384,134,1554,29,2101
1,1965-66,1966,444,134,1816,29,2423
2,1966-67,1967,466,134,2173,29,2802
3,1967-68,1968,472,137,2198,29,2836
4,1968-69,1969,472,137,2609,29,3247

In [115]:
df2 = pd.read_csv("../data/data-gov-india/railways-electrified-route-km-2015-2026.csv")

In [116]:
df2.head()

  Plan Period    FY  Target (RKM)  RKM Electrified  RKM Cumulative
0     2014-15  2015          1350             1176           22977
1     2015-16  2016          1600             1502           24479
2     2016-17  2017          2000             1646           26125
3     2017-18  2018          4000             4087           30212
4     2018-19  2019          6000             5276           35488

In [117]:
df.rename(columns={'Total': 'RKM Electrified Cumulative'}, inplace=True)
df2.rename(columns={'RKM Cumulative': 'RKM Electrified Cumulative'}, inplace=True)

In [118]:
combined_df = pd.concat([df[['FY', 'RKM Electrified Cumulative']], df2[['FY', 'RKM Electrified Cumulative']]])

In [119]:
display(combined_df.head())
display(combined_df.tail())

     FY  RKM Electrified Cumulative
0  1965                        2101
1  1966                        2423
2  1967                        2802
3  1968                        2836
4  1969                        3247

      FY  RKM Electrified Cumulative
7   2022                       52247
8   2023                       58812
9   2024                       66000
10  2025                       68701
11  2026                       69744

In [120]:
network_df = pd.read_csv("../data/data-gov-india/railways-total-network-km-1970-2013.csv")

In [121]:
network_df.head()

,Year,FY,Broad Gauge RKM,Metre Gauge RKM,Narrow Gauge RKM,Total Route Kms,Total Track Kms
0,1970-71,1971,29449.0,25865.0,4476.0,59790,98546
1,1971-72,1972,30041.0,25550.0,4476.0,60067,99807
2,1972-73,1973,30126.0,25547.0,4476.0,60149,100578
3,1973-74,1974,30210.0,25548.0,4476.0,60234,101028
4,1974-75,1975,30274.0,25551.0,4476.0,60301,101395

In [122]:
final_df = pd.merge(
    left=combined_df, right=network_df[['FY', 'Total Route Kms', 'Total Track Kms']], 
    on="FY"
    )

In [123]:
final_df.head(2)

     FY  RKM Electrified Cumulative  Total Route Kms  Total Track Kms
0  1971                        3706            59790            98546
1  1972                        3953            60067            99807

In [124]:
final_df['Electrification %'] = final_df['RKM Electrified Cumulative']/final_df['Total Route Kms']
final_df.head(2)

,FY,RKM Electrified Cumulative,Total Route Kms,Total Track Kms,Electrification %
0,1971,3706,59790,98546,0.061984
1,1972,3953,60067,99807,0.065810

In [125]:
final_df.tail()

,FY,RKM Electrified Cumulative,Total Route Kms,Total Track Kms,Electrification %
48,2020,39866,67956,126366,0.586644
49,2021,45881,68103,126611,0.673700
50,2022,52247,68043,128305,0.767853
51,2023,58812,68584,132310,0.857518
52,2024,66000,69181,135207,0.954019

In [126]:
with open('../data/data-gov-india/railways-network-stats-1971-2024.json', 'w') as f:
    json.dump(final_df.to_dict(orient='records'), f, indent=2)