In [405]:
import json
import pandas as pd

In [406]:
cap_df = pd.read_csv("../data/data-gov-india/electricity-installed-capacity.csv")

In [407]:
cap_df.head()

,Parameter,1948,1951,1957,1962,1967,1970,1975,1980,1981,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
0,Coal (in MW),756,1004,1597,2436,4417,6640,8652,14875,15991,...,192162.88,197171.5,200704.5,205134.5,209294.5,210699.5,211855.5,217589.46,221813,227830
1,Oil & Gas (in MW),98,149,228,300,486,410,406,332,433,...,26167.01,25735.09,25574.85,25465.07,25433.72,25409.22,25413.41,25627.41,25122.46,20711.62
2,Nuclear (in MW),-,-,-,-,-,-,640,640,640,...,6780,6780,6780,6780,6780,6780,6780,8180,8180,8780
3,Hydro (in MW),508,560,1061,1917,4124,5907,6966,10833,11384,...,44478.42,45293.42,45399.22,45699.22,46209.22,46722.52,46850.17,46928.17,47728.16,51164.66
4,Solar (in MW),-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-

In [408]:
columns = cap_df.columns.tolist()[1:]

In [409]:
# cap_df.pivot(columns=['Parameter'])
cap_df = cap_df.T
cap_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
Parameter,Coal (in MW),Oil & Gas (in MW),Nuclear (in MW),Hydro (in MW),Solar (in MW),Solar - Ground Mounted (in MW),Solar - Roof-top (in MW),Solar - Hybrid-solar (in MW),Solar - Off-grid (in MW),Wind (in MW),Small-Hydro (in MW),Bio Power (in MW),Bio-power - Bagasse (in MW),Bio-power - Non-bagasse (in MW),Bio-power - Waste-to-energy (in MW),Bio-power - Waste-to-energy-off-grid (in MW),RES-Total,Total,Growth Rate (in %)
1948,756,98,-,508,-,-,-,-,-,-,-,-,-,-,-,-,-,1362,NaN
1951,1004,149,-,560,-,-,-,-,-,-,-,-,-,-,-,-,-,1713,NaN
1957,1597,228,-,1061,-,-,-,-,-,-,-,-,-,-,-,-,-,2886,NaN
1962,2436,300,-,1917,-,-,-,-,-,-,-,-,-,-,-,-,-,4653,NaN
1967,4417,486,-,4124,-,-,-,-,-,-,-,-,-,-,-,-,-,9027,NaN
1970,6640,410,-,5907,-,-,-,-,-,-,-,-,-,-,-,-,-,12957,NaN
1975,8652,406,640,6966,-,-,-,-,-,-,-,-,-,-,-,-,-,16664,NaN
1980,14875,332,640,10833,-,-,-,-,-,-,-,-,-,-,-,-,-,26680,NaN
1981,15991,433,640,11384,-,-,-,-,-,-,-,-,-,-,-,-,-,28448,NaN
1986,26311,719,1095,14460,-,-,-,-,-,-,-,-,-,-,-,-,-,42585,NaN
1991,41237,2508,1565,18308,-,-,-,-,-,-,-,-,-,-,-,-,18,63636,NaN
1993,44791,3263,1785,19194,-,-,-,-,-,-,-,-,-,-,-,-,32,69065,NaN
1998,54154,6856,2225,21658,-,-,-,-,-,-,-,-,-,-,-,-,902,85795,NaN
2003,62131,12298,2720,26269,-,-,-,-,-,-,-,-,-,-,-,-,1628,105046,NaN
2007,71121.38,14893.47,3900,34653.78,-,-,-,-,-,-,-,-,-,-,-,-,7760.6,132329.23,NaN
2008,76018.88,15887.97,4120,35908.76,-,-,-,-,-,-,-,-,-,-,-,-,11125.41,143061.02,NaN
2009,77648.88,16076.36,4120,36877.76,2.12,-,-,-,-,9344.13,2160.48,1735.68,-,-,-,-,-,147965.41,NaN
2010,84198.38,18255.59,4560,36863.41,6,-,-,-,-,10647.45,2604.92,2262.74,-,-,-,-,-,159398.49,7.73
2011,93918.38,18906.1,4780,37567.41,32.39,-,-,-,-,12806.54,2913,2702.59,-,-,-,-,-,173626.41,8.93
2012,112022.38,19580.8,4780,38990.4,941.31,-,-,-,-,16896.6,3410.52,3255.01,-,-,-,-,-,199877.02,15.12
2013,130220.88,21309.6,4780,39491.4,1686.44,-,-,-,-,18484.99,3643.17,3727.11,-,-,-,-,-,223343.59,11.74
2014,145273.39,22981.6,4780,40531.41,-,2631.93,-,-,189.98,21042.58,3803.68,-,7419.23,531.82,90.58,139.79,-,249415.99,11.67
2015,164635.88,24261.9,5780,41267.42,-,3743.97,-,-,249.56,23354.35,4055.36,-,7714.9,591.87,90.58,149.5,-,275895.29,10.62
2016,185172.88,25502.16,5780,42783.42,-,6762.85,-,-,361.04,26777.4,4273.47,-,8019.75,651.11,90.58,155.19,-,306329.85,11.03
2017,192162.88,26167.01,6780,44478.42,-,12288.83,-,-,493.69,32279.77,4379.86,-,8181.7,653.31,114.08,166.96,-,328146.51,7.12
2018,197171.5,25735.09,6780,45293.42,-,20587.85,1063.63,-,694.73,34145,4485.81,-,8700.8,662.81,138.3,172.51,-,345631.45,5.33
2019,200704.5,25574.85,6780,45399.22,-,26384.32,1796.39,-,916.47,35625.97,4593.15,-,9103.5,674.81,138.3,179.09,-,357870.57,3.54
2020,205134.5,25465.07,6780,45699.22,-,32112.51,2515.31,-,979.42,37743.75,4683.16,-,9200.5,674.81,147.64,198.2,-,371334.09,3.76
2021,209294.5,25433.72,6780,46209.22,-,35645.63,4439.74,-,1150.65,39247.05,4786.81,-,9373.87,772.05,168.64,218.95,-,383520.83,3.28
2022,210699.5,25409.22,6780,46722.52,-,45793.19,6645.7,-,1557.65,40357.58,4848.9,-,9433.56,772.05,223.14,253.61,-,399496.62,4.17
2023,211855.5,25413.41,6780,46850.17,-,53802.38,8877.93,1707.14,2392.91,42633.13,4944.3,-,9433.56,814.45,248.14,305.89,-,416058.91,4.15
2024,217589.46,25627.41,8180,46928.17,-,64415.2,11869.63,2570.96,2957.81,45886.51,5003.25,-,9433.56,921.79,249.74,336.06,-,441969.55,6.23
2025,221813,25122.46,8180,47728.16,-,81011.66,17017.44,2874.5,4742.89,50037.82,5100.55,-,9821.32,921.79,309.34,530.87,-,475211.8,7.52
2026,227830,20711.62,8780,51164.66,-,107256.75,24298.55,3364.63,5681.8,54650.4,5158.61,-,9821.32,935.99,309.34,547.28,-,520510.95,NaN

In [410]:
cap_df.replace('-', 0, inplace=True)

In [411]:
cap_df.columns

RangeIndex(start=0, stop=19, step=1)

In [412]:
cap_df.columns = cap_df.iloc[0]
cap_df = cap_df[1:]

In [413]:
# cap_df.set_index(keys='Parameter')
print(cap_df.columns.tolist())
# print(cap_df.index)
# cap_df['Year'] = cap_df.index
# cap_df

['Coal (in MW)', 'Oil & Gas (in MW)', 'Nuclear (in MW)', 'Hydro (in MW)', 'Solar (in MW)', 'Solar - Ground Mounted (in MW)', 'Solar - Roof-top (in MW)', 'Solar - Hybrid-solar (in MW)', 'Solar - Off-grid (in MW)', 'Wind (in MW)', 'Small-Hydro (in MW)', 'Bio Power (in MW)', 'Bio-power - Bagasse (in MW)', 'Bio-power - Non-bagasse (in MW)', 'Bio-power - Waste-to-energy (in MW)', 'Bio-power - Waste-to-energy-off-grid (in MW)', 'RES-Total', 'Total', 'Growth Rate (in %)']

In [414]:
solar_columns = [
    "Solar - Ground Mounted (in MW)",
    "Solar - Roof-top (in MW)",
    "Solar - Hybrid-solar (in MW)",
    "Solar - Off-grid (in MW)",
]
biomass_columns = [
    "Bio-power - Bagasse (in MW)",
    "Bio-power - Non-bagasse (in MW)",
    "Bio-power - Waste-to-energy (in MW)",
    "Bio-power - Waste-to-energy-off-grid (in MW)",
]

In [415]:
cap_df.fillna(0, inplace=True)

for col in cap_df.columns:
    cap_df[col] = cap_df[col].astype(dtype=float)
    
# cap_df['Coal (in MW)'] = cap_df['Coal (in MW)'].astype(dtype=float)
# cap_df['Growth Rate (in %)'] = cap_df['Growth Rate (in %)'].astype(dtype=float)
# cap_df['Hydro (in MW)'] = cap_df['Coal (in MW)'].astype(dtype=float)

/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df.fillna(0, inplace=True)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3036048267.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df[col] = cap_df[col].astype(dtype=float)

In [416]:
cap_df['Solar (in MW)'] = cap_df[solar_columns[0]] + cap_df[solar_columns[1]] + cap_df[solar_columns[2]] + cap_df[solar_columns[3]]
cap_df['Bio Power (in MW)'] = cap_df[biomass_columns[0]] + cap_df[biomass_columns[1]] + cap_df[biomass_columns[2]] + cap_df[biomass_columns[3]]
cap_df['RES-Total'] = cap_df['Hydro (in MW)'] + cap_df['Solar (in MW)'] + cap_df['Wind (in MW)'] + cap_df['Bio Power (in MW)']

/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3146967095.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df['Solar (in MW)'] = cap_df[solar_columns[0]] + cap_df[solar_columns[1]] + cap_df[solar_columns[2]] + cap_df[solar_columns[3]]
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3146967095.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df['Bio Power (in MW)'] = cap_df[biomass_columns[0]] + cap_df[biomass_columns[1]] + cap_df[biomass_columns[2]] + cap_df[biomass_columns[3]]
/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/3146967095.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df['RES-Total'] = cap_df['Hydro (in MW)'] + cap_df['Solar (in MW)'] + cap_df['Wind (in MW)'] + cap_df['Bio Power (in MW)']

In [417]:
cap_df.rename(columns={
    'Coal (in MW)': 'Coal', 
    'Oil & Gas (in MW)': 'Oil & Gas', 
    'Nuclear (in MW)': 'Nuclear', 
    'Hydro (in MW)': 'Hydro', 
    'Solar (in MW)': 'Solar', 
    'Solar - Ground Mounted (in MW)': 'Solar - Ground Mounted', 
    'Solar - Roof-top (in MW)': 'Solar - Roof-top', 
    'Solar - Hybrid-solar (in MW)': 'Solar - Hybrid-solar', 
    'Solar - Off-grid (in MW)': 'Solar - Off-grid', 
    'Wind (in MW)': 'Wind', 
    'Small-Hydro (in MW)': 'Small-Hydro', 
    'Bio Power (in MW)': 'Bio Power', 
    'Bio-power - Bagasse (in MW)': 'Bio-power - Bagasse', 
    'Bio-power - Non-bagasse (in MW)': 'Bio-power - Non-bagasse', 
    'Bio-power - Waste-to-energy (in MW)': 'Bio-power - Waste-to-energy', 
    'Bio-power - Waste-to-energy-off-grid (in MW)': 'Bio-power - Waste-to-energy-off-grid', 
    }, inplace=True)

/var/folders/9y/ln_z5wqj0j33qrhqjlvsvzzh0000gn/T/ipykernel_47479/653968116.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cap_df.rename(columns={

In [418]:
data = cap_df.to_dict(orient='index')
data

{'1948': {'Coal': 756.0,
  'Oil & Gas': 98.0,
  'Nuclear': 0.0,
  'Hydro': 508.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 508.0,
  'Total': 1362.0,
  'Growth Rate (in %)': 0.0},
 '1951': {'Coal': 1004.0,
  'Oil & Gas': 149.0,
  'Nuclear': 0.0,
  'Hydro': 560.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 560.0,
  'Total': 1713.0,
  'Growth Rate (in %)': 0.0},
 '1957': {'Coal': 1597.0,
  'Oil & Gas': 228.0,
  'Nuclear': 0.0,
  'Hydro': 1061.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 1061.0,
  'Total': 2886.0,
  'Growth Rate (in %)': 0.0},
 '1962': {'Coal': 2436.0,
  'Oil & Gas': 300.0,
  'Nuclear': 0.0,
  'Hydro': 1917.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 1917.0,
  'Total': 4653.0,
  'Growth Rate (in %)': 0.0},
 '1967': {'Coal': 4417.0,
  'Oil & Gas': 486.0,
  'Nuclear': 0.0,
  'Hydro': 4124.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 4124.0,
  'Total': 9027.0,
  'Growth Rate (in %)': 0.0},
 '1970': {'Coal': 6640.0,
  'Oil & Gas': 410.0,
  'Nuclear': 0.0,
  'Hydro': 5907.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 5907.0,
  'Total': 12957.0,
  'Growth Rate (in %)': 0.0},
 '1975': {'Coal': 8652.0,
  'Oil & Gas': 406.0,
  'Nuclear': 640.0,
  'Hydro': 6966.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 6966.0,
  'Total': 16664.0,
  'Growth Rate (in %)': 0.0},
 '1980': {'Coal': 14875.0,
  'Oil & Gas': 332.0,
  'Nuclear': 640.0,
  'Hydro': 10833.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 10833.0,
  'Total': 26680.0,
  'Growth Rate (in %)': 0.0},
 '1981': {'Coal': 15991.0,
  'Oil & Gas': 433.0,
  'Nuclear': 640.0,
  'Hydro': 11384.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 11384.0,
  'Total': 28448.0,
  'Growth Rate (in %)': 0.0},
 '1986': {'Coal': 26311.0,
  'Oil & Gas': 719.0,
  'Nuclear': 1095.0,
  'Hydro': 14460.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 14460.0,
  'Total': 42585.0,
  'Growth Rate (in %)': 0.0},
 '1991': {'Coal': 41237.0,
  'Oil & Gas': 2508.0,
  'Nuclear': 1565.0,
  'Hydro': 18308.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 18308.0,
  'Total': 63636.0,
  'Growth Rate (in %)': 0.0},
 '1993': {'Coal': 44791.0,
  'Oil & Gas': 3263.0,
  'Nuclear': 1785.0,
  'Hydro': 19194.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 19194.0,
  'Total': 69065.0,
  'Growth Rate (in %)': 0.0},
 '1998': {'Coal': 54154.0,
  'Oil & Gas': 6856.0,
  'Nuclear': 2225.0,
  'Hydro': 21658.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 21658.0,
  'Total': 85795.0,
  'Growth Rate (in %)': 0.0},
 '2003': {'Coal': 62131.0,
  'Oil & Gas': 12298.0,
  'Nuclear': 2720.0,
  'Hydro': 26269.0,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 26269.0,
  'Total': 105046.0,
  'Growth Rate (in %)': 0.0},
 '2007': {'Coal': 71121.38,
  'Oil & Gas': 14893.47,
  'Nuclear': 3900.0,
  'Hydro': 34653.78,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 34653.78,
  'Total': 132329.23,
  'Growth Rate (in %)': 0.0},
 '2008': {'Coal': 76018.88,
  'Oil & Gas': 15887.97,
  'Nuclear': 4120.0,
  'Hydro': 35908.76,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 0.0,
  'Small-Hydro': 0.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 35908.76,
  'Total': 143061.02,
  'Growth Rate (in %)': 0.0},
 '2009': {'Coal': 77648.88,
  'Oil & Gas': 16076.36,
  'Nuclear': 4120.0,
  'Hydro': 36877.76,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 9344.13,
  'Small-Hydro': 2160.48,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 46221.89,
  'Total': 147965.41,
  'Growth Rate (in %)': 0.0},
 '2010': {'Coal': 84198.38,
  'Oil & Gas': 18255.59,
  'Nuclear': 4560.0,
  'Hydro': 36863.41,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 10647.45,
  'Small-Hydro': 2604.92,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 47510.86,
  'Total': 159398.49,
  'Growth Rate (in %)': 7.73},
 '2011': {'Coal': 93918.38,
  'Oil & Gas': 18906.1,
  'Nuclear': 4780.0,
  'Hydro': 37567.41,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 12806.54,
  'Small-Hydro': 2913.0,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 50373.950000000004,
  'Total': 173626.41,
  'Growth Rate (in %)': 8.93},
 '2012': {'Coal': 112022.38,
  'Oil & Gas': 19580.8,
  'Nuclear': 4780.0,
  'Hydro': 38990.4,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 16896.6,
  'Small-Hydro': 3410.52,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 55887.0,
  'Total': 199877.02,
  'Growth Rate (in %)': 15.12},
 '2013': {'Coal': 130220.88,
  'Oil & Gas': 21309.6,
  'Nuclear': 4780.0,
  'Hydro': 39491.4,
  'Solar': 0.0,
  'Solar - Ground Mounted': 0.0,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 0.0,
  'Wind': 18484.99,
  'Small-Hydro': 3643.17,
  'Bio Power': 0.0,
  'Bio-power - Bagasse': 0.0,
  'Bio-power - Non-bagasse': 0.0,
  'Bio-power - Waste-to-energy': 0.0,
  'Bio-power - Waste-to-energy-off-grid': 0.0,
  'RES-Total': 57976.39,
  'Total': 223343.59,
  'Growth Rate (in %)': 11.74},
 '2014': {'Coal': 145273.39,
  'Oil & Gas': 22981.6,
  'Nuclear': 4780.0,
  'Hydro': 40531.41,
  'Solar': 2821.91,
  'Solar - Ground Mounted': 2631.93,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 189.98,
  'Wind': 21042.58,
  'Small-Hydro': 3803.68,
  'Bio Power': 8181.419999999999,
  'Bio-power - Bagasse': 7419.23,
  'Bio-power - Non-bagasse': 531.82,
  'Bio-power - Waste-to-energy': 90.58,
  'Bio-power - Waste-to-energy-off-grid': 139.79,
  'RES-Total': 72577.32,
  'Total': 249415.99,
  'Growth Rate (in %)': 11.67},
 '2015': {'Coal': 164635.88,
  'Oil & Gas': 24261.9,
  'Nuclear': 5780.0,
  'Hydro': 41267.42,
  'Solar': 3993.5299999999997,
  'Solar - Ground Mounted': 3743.97,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 249.56,
  'Wind': 23354.35,
  'Small-Hydro': 4055.36,
  'Bio Power': 8546.85,
  'Bio-power - Bagasse': 7714.9,
  'Bio-power - Non-bagasse': 591.87,
  'Bio-power - Waste-to-energy': 90.58,
  'Bio-power - Waste-to-energy-off-grid': 149.5,
  'RES-Total': 77162.15,
  'Total': 275895.29,
  'Growth Rate (in %)': 10.62},
 '2016': {'Coal': 185172.88,
  'Oil & Gas': 25502.16,
  'Nuclear': 5780.0,
  'Hydro': 42783.42,
  'Solar': 7123.89,
  'Solar - Ground Mounted': 6762.85,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 361.04,
  'Wind': 26777.4,
  'Small-Hydro': 4273.47,
  'Bio Power': 8916.630000000001,
  'Bio-power - Bagasse': 8019.75,
  'Bio-power - Non-bagasse': 651.11,
  'Bio-power - Waste-to-energy': 90.58,
  'Bio-power - Waste-to-energy-off-grid': 155.19,
  'RES-Total': 85601.34,
  'Total': 306329.85,
  'Growth Rate (in %)': 11.03},
 '2017': {'Coal': 192162.88,
  'Oil & Gas': 26167.01,
  'Nuclear': 6780.0,
  'Hydro': 44478.42,
  'Solar': 12782.52,
  'Solar - Ground Mounted': 12288.83,
  'Solar - Roof-top': 0.0,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 493.69,
  'Wind': 32279.77,
  'Small-Hydro': 4379.86,
  'Bio Power': 9116.05,
  'Bio-power - Bagasse': 8181.7,
  'Bio-power - Non-bagasse': 653.31,
  'Bio-power - Waste-to-energy': 114.08,
  'Bio-power - Waste-to-energy-off-grid': 166.96,
  'RES-Total': 98656.76000000001,
  'Total': 328146.51,
  'Growth Rate (in %)': 7.12},
 '2018': {'Coal': 197171.5,
  'Oil & Gas': 25735.09,
  'Nuclear': 6780.0,
  'Hydro': 45293.42,
  'Solar': 22346.21,
  'Solar - Ground Mounted': 20587.85,
  'Solar - Roof-top': 1063.63,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 694.73,
  'Wind': 34145.0,
  'Small-Hydro': 4485.81,
  'Bio Power': 9674.419999999998,
  'Bio-power - Bagasse': 8700.8,
  'Bio-power - Non-bagasse': 662.81,
  'Bio-power - Waste-to-energy': 138.3,
  'Bio-power - Waste-to-energy-off-grid': 172.51,
  'RES-Total': 111459.05,
  'Total': 345631.45,
  'Growth Rate (in %)': 5.33},
 '2019': {'Coal': 200704.5,
  'Oil & Gas': 25574.85,
  'Nuclear': 6780.0,
  'Hydro': 45399.22,
  'Solar': 29097.18,
  'Solar - Ground Mounted': 26384.32,
  'Solar - Roof-top': 1796.39,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 916.47,
  'Wind': 35625.97,
  'Small-Hydro': 4593.15,
  'Bio Power': 10095.699999999999,
  'Bio-power - Bagasse': 9103.5,
  'Bio-power - Non-bagasse': 674.81,
  'Bio-power - Waste-to-energy': 138.3,
  'Bio-power - Waste-to-energy-off-grid': 179.09,
  'RES-Total': 120218.06999999999,
  'Total': 357870.57,
  'Growth Rate (in %)': 3.54},
 '2020': {'Coal': 205134.5,
  'Oil & Gas': 25465.07,
  'Nuclear': 6780.0,
  'Hydro': 45699.22,
  'Solar': 35607.24,
  'Solar - Ground Mounted': 32112.51,
  'Solar - Roof-top': 2515.31,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 979.42,
  'Wind': 37743.75,
  'Small-Hydro': 4683.16,
  'Bio Power': 10221.15,
  'Bio-power - Bagasse': 9200.5,
  'Bio-power - Non-bagasse': 674.81,
  'Bio-power - Waste-to-energy': 147.64,
  'Bio-power - Waste-to-energy-off-grid': 198.2,
  'RES-Total': 129271.35999999999,
  'Total': 371334.09,
  'Growth Rate (in %)': 3.76},
 '2021': {'Coal': 209294.5,
  'Oil & Gas': 25433.72,
  'Nuclear': 6780.0,
  'Hydro': 46209.22,
  'Solar': 41236.02,
  'Solar - Ground Mounted': 35645.63,
  'Solar - Roof-top': 4439.74,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 1150.65,
  'Wind': 39247.05,
  'Small-Hydro': 4786.81,
  'Bio Power': 10533.51,
  'Bio-power - Bagasse': 9373.87,
  'Bio-power - Non-bagasse': 772.05,
  'Bio-power - Waste-to-energy': 168.64,
  'Bio-power - Waste-to-energy-off-grid': 218.95,
  'RES-Total': 137225.8,
  'Total': 383520.83,
  'Growth Rate (in %)': 3.28},
 '2022': {'Coal': 210699.5,
  'Oil & Gas': 25409.22,
  'Nuclear': 6780.0,
  'Hydro': 46722.52,
  'Solar': 53996.54,
  'Solar - Ground Mounted': 45793.19,
  'Solar - Roof-top': 6645.7,
  'Solar - Hybrid-solar': 0.0,
  'Solar - Off-grid': 1557.65,
  'Wind': 40357.58,
  'Small-Hydro': 4848.9,
  'Bio Power': 10682.359999999999,
  'Bio-power - Bagasse': 9433.56,
  'Bio-power - Non-bagasse': 772.05,
  'Bio-power - Waste-to-energy': 223.14,
  'Bio-power - Waste-to-energy-off-grid': 253.61,
  'RES-Total': 151759.0,
  'Total': 399496.62,
  'Growth Rate (in %)': 4.17},
 '2023': {'Coal': 211855.5,
  'Oil & Gas': 25413.41,
  'Nuclear': 6780.0,
  'Hydro': 46850.17,
  'Solar': 66780.36,
  'Solar - Ground Mounted': 53802.38,
  'Solar - Roof-top': 8877.93,
  'Solar - Hybrid-solar': 1707.14,
  'Solar - Off-grid': 2392.91,
  'Wind': 42633.13,
  'Small-Hydro': 4944.3,
  'Bio Power': 10802.039999999999,
  'Bio-power - Bagasse': 9433.56,
  'Bio-power - Non-bagasse': 814.45,
  'Bio-power - Waste-to-energy': 248.14,
  'Bio-power - Waste-to-energy-off-grid': 305.89,
  'RES-Total': 167065.7,
  'Total': 416058.91,
  'Growth Rate (in %)': 4.15},
 '2024': {'Coal': 217589.46,
  'Oil & Gas': 25627.41,
  'Nuclear': 8180.0,
  'Hydro': 46928.17,
  'Solar': 81813.6,
  'Solar - Ground Mounted': 64415.2,
  'Solar - Roof-top': 11869.63,
  'Solar - Hybrid-solar': 2570.96,
  'Solar - Off-grid': 2957.81,
  'Wind': 45886.51,
  'Small-Hydro': 5003.25,
  'Bio Power': 10941.149999999998,
  'Bio-power - Bagasse': 9433.56,
  'Bio-power - Non-bagasse': 921.79,
  'Bio-power - Waste-to-energy': 249.74,
  'Bio-power - Waste-to-energy-off-grid': 336.06,
  'RES-Total': 185569.43,
  'Total': 441969.55,
  'Growth Rate (in %)': 6.23},
 '2025': {'Coal': 221813.0,
  'Oil & Gas': 25122.46,
  'Nuclear': 8180.0,
  'Hydro': 47728.16,
  'Solar': 105646.49,
  'Solar - Ground Mounted': 81011.66,
  'Solar - Roof-top': 17017.44,
  'Solar - Hybrid-solar': 2874.5,
  'Solar - Off-grid': 4742.89,
  'Wind': 50037.82,
  'Small-Hydro': 5100.55,
  'Bio Power': 11583.320000000002,
  'Bio-power - Bagasse': 9821.32,
  'Bio-power - Non-bagasse': 921.79,
  'Bio-power - Waste-to-energy': 309.34,
  'Bio-power - Waste-to-energy-off-grid': 530.87,
  'RES-Total': 214995.79000000004,
  'Total': 475211.8,
  'Growth Rate (in %)': 7.52},
 '2026': {'Coal': 227830.0,
  'Oil & Gas': 20711.62,
  'Nuclear': 8780.0,
  'Hydro': 51164.66,
  'Solar': 140601.72999999998,
  'Solar - Ground Mounted': 107256.75,
  'Solar - Roof-top': 24298.55,
  'Solar - Hybrid-solar': 3364.63,
  'Solar - Off-grid': 5681.8,
  'Wind': 54650.4,
  'Small-Hydro': 5158.61,
  'Bio Power': 11613.93,
  'Bio-power - Bagasse': 9821.32,
  'Bio-power - Non-bagasse': 935.99,
  'Bio-power - Waste-to-energy': 309.34,
  'Bio-power - Waste-to-energy-off-grid': 547.28,
  'RES-Total': 258030.71999999997,
  'Total': 520510.95,
  'Growth Rate (in %)': 0.0}}

In [419]:
cap_df.head()

Parameter,Coal,Oil & Gas,Nuclear,Hydro,Solar,Solar - Ground Mounted,Solar - Roof-top,Solar - Hybrid-solar,Solar - Off-grid,Wind,Small-Hydro,Bio Power,Bio-power - Bagasse,Bio-power - Non-bagasse,Bio-power - Waste-to-energy,Bio-power - Waste-to-energy-off-grid,RES-Total,Total,Growth Rate (in %)
1948,756.0,98.0,0.0,508.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,508.0,1362.0,0.0
1951,1004.0,149.0,0.0,560.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,560.0,1713.0,0.0
1957,1597.0,228.0,0.0,1061.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1061.0,2886.0,0.0
1962,2436.0,300.0,0.0,1917.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1917.0,4653.0,0.0
1967,4417.0,486.0,0.0,4124.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4124.0,9027.0,0.0

In [420]:
# Dump to cleanly indented JSON
with open("../data/electricity-installed-capacity.json", "w") as f:
    json.dump({'indicator': 'Power Installed Capacity', 'unit': 'MW', 'data': {'IND': data}}, f, indent=2)

In [421]:
gen_df = pd.read_csv("../data/data-gov-india/electricity-power-generation.csv")
gen_df

,Parameter,1948,1951,1957,1962,1967,1970,1975,1980,1981,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
0,Coal - Generation (in MU),1733,2587,5367,9100,17765,26711,34853,52024,55720,...,944021.83,986590.65,1022265.32,994196.99,981443.23,1078581.47,1182095.84,1294852.39,1331867.06,1056429.09
1,Oil & Gas - Generation (in MU),144,200,233,368,393,318,468,570,553,...,49494.51,50555.73,50048.84,48641.17,51167.54,36229.92,24114.75,31696.52,32022.7,23126.8
2,Nuclear - Generation (in MU),-,-,-,-,-,-,2396,2770,2876,...,37915.87,38346.12,37812.6,46472.45,43029.08,47112.06,45861.09,47937.41,56680.83,45177.62
3,Hydro - Generation (in MU),2195,2519,4295,7837,15225,20723,28972,47159,45478,...,122377.56,126122.7,134893.62,155769.12,150299.52,151627.33,162098.77,134053.92,148633.98,150027.35
4,Solar - Generation (in MU),-,-,-,-,-,-,-,-,-,...,13499.41,25871.07,39268.2,50131.1,60402.25,73483.94,102014.24,115975.11,144150.23,137511.15
5,Wind - Generation (in MU),-,-,-,-,-,-,-,-,-,...,46004.34,52666.09,62036.38,64646.37,60149.9,68640.07,71814.16,83385.35,83347.19,94811.01
6,Small-Hydro - Generation (in MU),-,-,-,-,-,-,-,-,-,...,7672.66,7691.58,8702.75,9451.22,10258.41,10463.54,11170.61,9485.04,11568.04,10476.19
7,Bio Power - Generation (in MU),-,-,-,-,-,-,-,-,-,...,14371.8,15610.75,16751.77,14108.31,16436.89,18324.75,18553.66,16989.33,15943.72,11553.76
8,RES-Total - Generation,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
9,Total,4072,5306,9895,17305,33383,47752,66689,102523,104627,...,1235357.98,1303454.69,1371779.48,1383416.73,1373186.82,1484463.08,1617723.12,1734375.07,1824213.75,1529112.97
10,Growth Rate (in %),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.8,5.51,5.24,0.85,-0.74,8.1,8.98,7.21,5.18,NaN

In [422]:
gen_df = gen_df.T

gen_df.replace('-', 0, inplace=True)

gen_df.columns = gen_df.iloc[0]
gen_df = gen_df[1:]

gen_df.fillna(0, inplace=True)

for col in gen_df.columns:
    gen_df[col] = gen_df[col].astype(dtype=float)

display(gen_df)

Parameter,Coal - Generation (in MU),Oil & Gas - Generation (in MU),Nuclear - Generation (in MU),Hydro - Generation (in MU),Solar - Generation (in MU),Wind - Generation (in MU),Small-Hydro - Generation (in MU),Bio Power - Generation (in MU),RES-Total - Generation,Total,Growth Rate (in %)
1948,1733.00,144.00,0.00,2195.00,0.00,0.00,0.00,0.00,0.00,4072.00,0.00
1951,2587.00,200.00,0.00,2519.00,0.00,0.00,0.00,0.00,0.00,5306.00,0.00
1957,5367.00,233.00,0.00,4295.00,0.00,0.00,0.00,0.00,0.00,9895.00,0.00
1962,9100.00,368.00,0.00,7837.00,0.00,0.00,0.00,0.00,0.00,17305.00,0.00
1967,17765.00,393.00,0.00,15225.00,0.00,0.00,0.00,0.00,0.00,33383.00,0.00
1970,26711.00,318.00,0.00,20723.00,0.00,0.00,0.00,0.00,0.00,47752.00,0.00
1975,34853.00,468.00,2396.00,28972.00,0.00,0.00,0.00,0.00,0.00,66689.00,0.00
1980,52024.00,570.00,2770.00,47159.00,0.00,0.00,0.00,0.00,0.00,102523.00,0.00
1981,55720.00,553.00,2876.00,45478.00,0.00,0.00,0.00,0.00,0.00,104627.00,0.00
1986,96957.00,1879.00,4075.00,53948.00,0.00,0.00,0.00,0.00,0.00,156859.00,0.00
1991,172643.00,6047.00,4625.00,62116.00,0.00,0.00,0.00,0.00,6.00,245437.00,0.00
1993,197163.00,11545.00,5525.00,72757.00,0.00,0.00,0.00,0.00,38.00,287028.00,0.00
1998,289378.00,27664.00,9071.00,68901.00,0.00,0.00,0.00,0.00,876.00,395890.00,0.00
2003,370884.00,51416.00,19475.00,73579.00,0.00,0.00,0.00,0.00,2085.00,517439.00,0.00
2007,461794.18,66696.23,18802.00,113501.64,0.00,0.00,0.00,0.00,9860.11,670654.16,0.00
2008,486998.16,73073.62,16957.00,120386.72,0.00,0.00,0.00,0.00,25210.00,722625.50,0.00
2009,511895.05,76386.78,14927.00,110098.53,0.00,0.00,0.00,0.00,27860.00,741167.36,0.00
2010,539586.39,100621.37,18636.44,104059.39,0.00,0.00,0.00,0.00,36947.01,799850.60,7.92
2011,561298.07,103523.68,26266.40,114415.52,0.00,0.00,0.00,0.00,39244.54,844748.21,5.61
2012,612497.08,95930.03,32286.56,130511.47,0.00,0.00,0.00,0.00,51226.05,922451.19,9.20
2013,691341.21,69112.35,32866.11,113720.29,0.00,0.00,0.00,0.00,57448.91,964488.87,4.56
2014,745533.10,46520.47,34227.79,134847.53,0.00,0.00,0.00,0.00,65519.69,1026648.58,6.44
2015,835290.78,42650.71,36101.54,129243.69,4599.02,33768.30,8059.50,15292.42,0.00,1105005.96,7.63
2016,895339.83,47673.09,37413.62,121376.65,7447.94,33029.39,8354.51,16949.03,0.00,1167584.06,5.66
2017,944021.83,49494.51,37915.87,122377.56,13499.41,46004.34,7672.66,14371.80,0.00,1235357.98,5.80
2018,986590.65,50555.73,38346.12,126122.70,25871.07,52666.09,7691.58,15610.75,0.00,1303454.69,5.51
2019,1022265.32,50048.84,37812.60,134893.62,39268.20,62036.38,8702.75,16751.77,0.00,1371779.48,5.24
2020,994196.99,48641.17,46472.45,155769.12,50131.10,64646.37,9451.22,14108.31,0.00,1383416.73,0.85
2021,981443.23,51167.54,43029.08,150299.52,60402.25,60149.90,10258.41,16436.89,0.00,1373186.82,-0.74
2022,1078581.47,36229.92,47112.06,151627.33,73483.94,68640.07,10463.54,18324.75,0.00,1484463.08,8.10
2023,1182095.84,24114.75,45861.09,162098.77,102014.24,71814.16,11170.61,18553.66,0.00,1617723.12,8.98
2024,1294852.39,31696.52,47937.41,134053.92,115975.11,83385.35,9485.04,16989.33,0.00,1734375.07,7.21
2025,1331867.06,32022.70,56680.83,148633.98,144150.23,83347.19,11568.04,15943.72,0.00,1824213.75,5.18
2026,1056429.09,23126.80,45177.62,150027.35,137511.15,94811.01,10476.19,11553.76,0.00,1529112.97,0.00

In [423]:
gen_df.columns.tolist()

['Coal - Generation (in MU)',
 'Oil & Gas - Generation (in MU)',
 'Nuclear - Generation (in MU)',
 'Hydro - Generation (in MU)',
 'Solar - Generation (in MU)',
 'Wind - Generation (in MU)',
 'Small-Hydro - Generation (in MU)',
 'Bio Power - Generation (in MU)',
 'RES-Total - Generation',
 'Total',
 'Growth Rate (in %)']

In [424]:
hydro_generation_columns = [
    "Hydro - Generation (in MU)",
    "Small-Hydro - Generation (in MU)",
]
# gen_df['Solar (in MU)'] = gen_df[solar_columns[0]] + gen_df[solar_columns[1]] + gen_df[solar_columns[2]] + gen_df[solar_columns[3]]
# gen_df['Bio Power (in MU)'] = gen_df[biomass_columns[0]] + gen_df[biomass_columns[1]] + gen_df[biomass_columns[2]] + gen_df[biomass_columns[3]]
gen_df["Hydro - Generation (in MU)"] = (
    gen_df[hydro_generation_columns[0]] + gen_df[hydro_generation_columns[1]]
)
gen_df["RES-Total - Generation"] = (
    gen_df["Hydro - Generation (in MU)"]
    + gen_df["Solar - Generation (in MU)"]
    + gen_df["Wind - Generation (in MU)"]
    + gen_df["Bio Power - Generation (in MU)"]
)

gen_df.columns = [
    "Coal",
    "Oil & Gas",
    "Nuclear",
    "Hydro",
    "Solar",
    "Wind",
    "Small-Hydro",
    "Bio Power",
    "RES-Total",
    "Total",
    "Growth Rate (in %)",
]

In [425]:
gen_df.head(2)

,Coal,Oil & Gas,Nuclear,Hydro,Solar,Wind,Small-Hydro,Bio Power,RES-Total,Total,Growth Rate (in %)
1948,1733.0,144.0,0.0,2195.0,0.0,0.0,0.0,0.0,2195.0,4072.0,0.0
1951,2587.0,200.0,0.0,2519.0,0.0,0.0,0.0,0.0,2519.0,5306.0,0.0

In [426]:
gen_df.drop(columns=['Small-Hydro'], inplace=True)

gen_data = gen_df.to_dict(orient='index')
gen_data

{'1948': {'Coal': 1733.0,
  'Oil & Gas': 144.0,
  'Nuclear': 0.0,
  'Hydro': 2195.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 2195.0,
  'Total': 4072.0,
  'Growth Rate (in %)': 0.0},
 '1951': {'Coal': 2587.0,
  'Oil & Gas': 200.0,
  'Nuclear': 0.0,
  'Hydro': 2519.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 2519.0,
  'Total': 5306.0,
  'Growth Rate (in %)': 0.0},
 '1957': {'Coal': 5367.0,
  'Oil & Gas': 233.0,
  'Nuclear': 0.0,
  'Hydro': 4295.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 4295.0,
  'Total': 9895.0,
  'Growth Rate (in %)': 0.0},
 '1962': {'Coal': 9100.0,
  'Oil & Gas': 368.0,
  'Nuclear': 0.0,
  'Hydro': 7837.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 7837.0,
  'Total': 17305.0,
  'Growth Rate (in %)': 0.0},
 '1967': {'Coal': 17765.0,
  'Oil & Gas': 393.0,
  'Nuclear': 0.0,
  'Hydro': 15225.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 15225.0,
  'Total': 33383.0,
  'Growth Rate (in %)': 0.0},
 '1970': {'Coal': 26711.0,
  'Oil & Gas': 318.0,
  'Nuclear': 0.0,
  'Hydro': 20723.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 20723.0,
  'Total': 47752.0,
  'Growth Rate (in %)': 0.0},
 '1975': {'Coal': 34853.0,
  'Oil & Gas': 468.0,
  'Nuclear': 2396.0,
  'Hydro': 28972.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 28972.0,
  'Total': 66689.0,
  'Growth Rate (in %)': 0.0},
 '1980': {'Coal': 52024.0,
  'Oil & Gas': 570.0,
  'Nuclear': 2770.0,
  'Hydro': 47159.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 47159.0,
  'Total': 102523.0,
  'Growth Rate (in %)': 0.0},
 '1981': {'Coal': 55720.0,
  'Oil & Gas': 553.0,
  'Nuclear': 2876.0,
  'Hydro': 45478.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 45478.0,
  'Total': 104627.0,
  'Growth Rate (in %)': 0.0},
 '1986': {'Coal': 96957.0,
  'Oil & Gas': 1879.0,
  'Nuclear': 4075.0,
  'Hydro': 53948.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 53948.0,
  'Total': 156859.0,
  'Growth Rate (in %)': 0.0},
 '1991': {'Coal': 172643.0,
  'Oil & Gas': 6047.0,
  'Nuclear': 4625.0,
  'Hydro': 62116.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 62116.0,
  'Total': 245437.0,
  'Growth Rate (in %)': 0.0},
 '1993': {'Coal': 197163.0,
  'Oil & Gas': 11545.0,
  'Nuclear': 5525.0,
  'Hydro': 72757.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 72757.0,
  'Total': 287028.0,
  'Growth Rate (in %)': 0.0},
 '1998': {'Coal': 289378.0,
  'Oil & Gas': 27664.0,
  'Nuclear': 9071.0,
  'Hydro': 68901.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 68901.0,
  'Total': 395890.0,
  'Growth Rate (in %)': 0.0},
 '2003': {'Coal': 370884.0,
  'Oil & Gas': 51416.0,
  'Nuclear': 19475.0,
  'Hydro': 73579.0,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 73579.0,
  'Total': 517439.0,
  'Growth Rate (in %)': 0.0},
 '2007': {'Coal': 461794.18,
  'Oil & Gas': 66696.23,
  'Nuclear': 18802.0,
  'Hydro': 113501.64,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 113501.64,
  'Total': 670654.16,
  'Growth Rate (in %)': 0.0},
 '2008': {'Coal': 486998.16,
  'Oil & Gas': 73073.62,
  'Nuclear': 16957.0,
  'Hydro': 120386.72,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 120386.72,
  'Total': 722625.5,
  'Growth Rate (in %)': 0.0},
 '2009': {'Coal': 511895.05,
  'Oil & Gas': 76386.78,
  'Nuclear': 14927.0,
  'Hydro': 110098.53,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 110098.53,
  'Total': 741167.36,
  'Growth Rate (in %)': 0.0},
 '2010': {'Coal': 539586.39,
  'Oil & Gas': 100621.37,
  'Nuclear': 18636.44,
  'Hydro': 104059.39,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 104059.39,
  'Total': 799850.6,
  'Growth Rate (in %)': 7.92},
 '2011': {'Coal': 561298.07,
  'Oil & Gas': 103523.68,
  'Nuclear': 26266.4,
  'Hydro': 114415.52,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 114415.52,
  'Total': 844748.21,
  'Growth Rate (in %)': 5.61},
 '2012': {'Coal': 612497.08,
  'Oil & Gas': 95930.03,
  'Nuclear': 32286.56,
  'Hydro': 130511.47,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 130511.47,
  'Total': 922451.19,
  'Growth Rate (in %)': 9.2},
 '2013': {'Coal': 691341.21,
  'Oil & Gas': 69112.35,
  'Nuclear': 32866.11,
  'Hydro': 113720.29,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 113720.29,
  'Total': 964488.87,
  'Growth Rate (in %)': 4.56},
 '2014': {'Coal': 745533.1,
  'Oil & Gas': 46520.47,
  'Nuclear': 34227.79,
  'Hydro': 134847.53,
  'Solar': 0.0,
  'Wind': 0.0,
  'Bio Power': 0.0,
  'RES-Total': 134847.53,
  'Total': 1026648.58,
  'Growth Rate (in %)': 6.44},
 '2015': {'Coal': 835290.78,
  'Oil & Gas': 42650.71,
  'Nuclear': 36101.54,
  'Hydro': 137303.19,
  'Solar': 4599.02,
  'Wind': 33768.3,
  'Bio Power': 15292.42,
  'RES-Total': 190962.93000000002,
  'Total': 1105005.96,
  'Growth Rate (in %)': 7.63},
 '2016': {'Coal': 895339.83,
  'Oil & Gas': 47673.09,
  'Nuclear': 37413.62,
  'Hydro': 129731.15999999999,
  'Solar': 7447.94,
  'Wind': 33029.39,
  'Bio Power': 16949.03,
  'RES-Total': 187157.52,
  'Total': 1167584.06,
  'Growth Rate (in %)': 5.66},
 '2017': {'Coal': 944021.83,
  'Oil & Gas': 49494.51,
  'Nuclear': 37915.87,
  'Hydro': 130050.22,
  'Solar': 13499.41,
  'Wind': 46004.34,
  'Bio Power': 14371.8,
  'RES-Total': 203925.77,
  'Total': 1235357.98,
  'Growth Rate (in %)': 5.8},
 '2018': {'Coal': 986590.65,
  'Oil & Gas': 50555.73,
  'Nuclear': 38346.12,
  'Hydro': 133814.28,
  'Solar': 25871.07,
  'Wind': 52666.09,
  'Bio Power': 15610.75,
  'RES-Total': 227962.19,
  'Total': 1303454.69,
  'Growth Rate (in %)': 5.51},
 '2019': {'Coal': 1022265.32,
  'Oil & Gas': 50048.84,
  'Nuclear': 37812.6,
  'Hydro': 143596.37,
  'Solar': 39268.2,
  'Wind': 62036.38,
  'Bio Power': 16751.77,
  'RES-Total': 261652.72,
  'Total': 1371779.48,
  'Growth Rate (in %)': 5.24},
 '2020': {'Coal': 994196.99,
  'Oil & Gas': 48641.17,
  'Nuclear': 46472.45,
  'Hydro': 165220.34,
  'Solar': 50131.1,
  'Wind': 64646.37,
  'Bio Power': 14108.31,
  'RES-Total': 294106.12,
  'Total': 1383416.73,
  'Growth Rate (in %)': 0.85},
 '2021': {'Coal': 981443.23,
  'Oil & Gas': 51167.54,
  'Nuclear': 43029.08,
  'Hydro': 160557.93,
  'Solar': 60402.25,
  'Wind': 60149.9,
  'Bio Power': 16436.89,
  'RES-Total': 297546.97000000003,
  'Total': 1373186.82,
  'Growth Rate (in %)': -0.74},
 '2022': {'Coal': 1078581.47,
  'Oil & Gas': 36229.92,
  'Nuclear': 47112.06,
  'Hydro': 162090.87,
  'Solar': 73483.94,
  'Wind': 68640.07,
  'Bio Power': 18324.75,
  'RES-Total': 322539.63,
  'Total': 1484463.08,
  'Growth Rate (in %)': 8.1},
 '2023': {'Coal': 1182095.84,
  'Oil & Gas': 24114.75,
  'Nuclear': 45861.09,
  'Hydro': 173269.38,
  'Solar': 102014.24,
  'Wind': 71814.16,
  'Bio Power': 18553.66,
  'RES-Total': 365651.44,
  'Total': 1617723.12,
  'Growth Rate (in %)': 8.98},
 '2024': {'Coal': 1294852.39,
  'Oil & Gas': 31696.52,
  'Nuclear': 47937.41,
  'Hydro': 143538.96000000002,
  'Solar': 115975.11,
  'Wind': 83385.35,
  'Bio Power': 16989.33,
  'RES-Total': 359888.75000000006,
  'Total': 1734375.07,
  'Growth Rate (in %)': 7.21},
 '2025': {'Coal': 1331867.06,
  'Oil & Gas': 32022.7,
  'Nuclear': 56680.83,
  'Hydro': 160202.02000000002,
  'Solar': 144150.23,
  'Wind': 83347.19,
  'Bio Power': 15943.72,
  'RES-Total': 403643.16,
  'Total': 1824213.75,
  'Growth Rate (in %)': 5.18},
 '2026': {'Coal': 1056429.09,
  'Oil & Gas': 23126.8,
  'Nuclear': 45177.62,
  'Hydro': 160503.54,
  'Solar': 137511.15,
  'Wind': 94811.01,
  'Bio Power': 11553.76,
  'RES-Total': 404379.46,
  'Total': 1529112.97,
  'Growth Rate (in %)': 0.0}}

In [427]:
# Dump to cleanly indented JSON
with open("../data/electricity-power-generation.json", "w") as f:
    json.dump({'indicator': 'Power Generation', 'unit': 'MU', 'data': {'IND': gen_data}}, f, indent=2)